### PR TITLE
Fix for asteroid factories + update v0.15.7 r10228

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Laserzwei** [comment]
Thank you very much for helping me make the complex mod compatible with 0.15.7
1 f5f0e8d05c0fa94910ff7529d366582832e0a08a
doesn't fix tradingutility. In short: `254 return error` overwrites the return at the end of the file. 

2 72720f38b130b81756e58dada37e1841619e0258 is fine. 
1&2 are included here(I had it changed in my Editor, but no commit yet):
77570230315ab739c620099df8071ca88d1c8689

3 47e1fc80356d1f0564dd8242e5f203d826b46d02 oopsi on my side :D 

4 7477cff3a38844344a4f7dc04fa06e16eb680fcd
### I refuse to hook into minefounder.lua

**Comment by ghost** [comment]
> doesn't fix tradingutility. In short: 254 return error overwrites the return at the end of the file.
> 1&2 are included here(I had it changed in my Editor, but no commit yet):

It is from vanilla file. Not my code.


> I refuse to hook into minefounder.lua

For now, mines are not even have "Complex" menu. Tested it with vanilla + complex mod on wiped server.
After adding https://github.com/Laserzwei/complex/commit/7477cff3a38844344a4f7dc04fa06e16eb680fcd#diff-efb8f2f5db0de7b5c2dd8bd9a182db6fR300 and https://github.com/Laserzwei/complex/commit/7477cff3a38844344a4f7dc04fa06e16eb680fcd#diff-efb8f2f5db0de7b5c2dd8bd9a182db6fR301 it was fixed.

**Comment by Laserzwei** [comment]
> For now, mines are not even have "Complex" menu.

And your "fix" changes it properly, BUT:
The current limitation on stations  is actually intended and mentioned here: 
https://github.com/Laserzwei/complex/wiki/Start-your-first-complex

However they should be selectable from any build factory (non -Mine/ -Oil Rig) in the construction tab.

**Comment by ghost** [comment]
> Thank you very much for helping me make the complex mod

You are welcome. I was charmed by your mod. So trying hard to use it on our public server.

**Pull request closed without merging**
